### ISSUE TITLE
Latest build (#17) doesn't work (java.lang.Exception: Unable to load plugin)

### ISSUE THREAD

**Issue by riomccloud** [RaphiMC/ViaProxyGeyserPlugin#1]
The latest build of ViaProxyGeyserPlugin (#17) cannot be loaded by ViaProxy. However, the build #16 works as intended.

![image](https://github.com/RaphiMC/ViaProxyGeyserPlugin/assets/32412883/931930c7-e8bb-4835-acb5-793507f0053c)

**Comment by RaphiMC** [comment]
This happens because the latest build of the geyser plugin requires at least ViaProxy 3.0.19 (Which is currently not yet released, but will be on 07.06). You can download a dev build of it here: https://ci.viaversion.com/view/All/job/ViaProxy/
